name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Deploy via SSH to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Defina caminhos
            PROJECT_PATH="/www/wwwroot/caiobook"
            LOG_DIR="$PROJECT_PATH/logs/deploy"

            # 1) prepara diretório de logs
            mkdir -p "$LOG_DIR"
            chmod 755 "$LOG_DIR"

            # 2) nome do arquivo de log com timestamp
            TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
            LOG_FILE="$LOG_DIR/deploy-$TIMESTAMP.log"

            echo "=== Deploy iniciado em $(date) ===" >> "$LOG_FILE"
            # todo output daqui em diante vai para o log e console
            exec > >(tee -a "$LOG_FILE") 2>&1

            # 3) entra no diretório do projeto
            cd "$PROJECT_PATH" || { echo "Diretório $PROJECT_PATH não encontrado"; exit 1; }

            # 4) atualiza o código
            echo "--- Atualizando código ---"
            git pull origin main

            # 5) (re)cria e ativa o venv e instala dependências
            echo "--- Preparando ambiente Python ---"
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # 6) reinicia o serviço systemd
            echo "--- Reiniciando meu_notion.service ---"
            sudo systemctl restart meu_notion.service \
              && echo "Serviço reiniciado com sucesso." \
              || echo "Falha ao reiniciar serviço."

            echo "=== Deploy finalizado em $(date) ==="
            echo "Logs salvos em $LOG_FILE"
            echo "Verifique o status do serviço com: sudo systemctl status meu_notion.service"
            echo "Verifique os logs do serviço com: journalctl -u meu_notion.service -f"