name: Deploy to Server

on:
  push:
    branches:
      - main

env:
  PROJECT_PATH: /www/wwwroot/caiobook

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Deploy via SSH to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # monta LOG_DIR a partir de PROJECT_PATH
            LOG_DIR="${PROJECT_PATH}/logs/deploy"
            mkdir -p "$LOG_DIR"
            chmod 755 "$LOG_DIR"

            TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
            LOG_FILE="$LOG_DIR/deploy-$TIMESTAMP.log"

            echo "=== Deploy iniciado em $(date) ===" >> "$LOG_FILE"
            exec > >(tee -a "$LOG_FILE") 2>&1

            cd "$PROJECT_PATH" || { echo "Diretório $PROJECT_PATH não encontrado"; exit 1; }

            echo "--- Atualizando código ---"
            git pull origin main

            echo "--- Preparando ambiente Python ---"
            [ ! -d venv ] && python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            echo "--- Reiniciando meu_notion.service ---"
            sudo systemctl restart meu_notion.service \
              && echo "Serviço reiniciado com sucesso." \
              || echo "Falha ao reiniciar serviço."

            echo "=== Deploy finalizado em $(date) ==="
            echo "Logs disponíveis em $LOG_FILE"