name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository (runner)
        uses: actions/checkout@v3

      - name: Set up Python (runner)
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      # Essa etapa é opcional e roda no runner (não no servidor)
      - name: Install dependencies on runner (optional)
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy via SSH to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Acesse o diretório do projeto no servidor
            cd /www/wwwroot/Caiobook || { echo "Diretório /www/wwwroot/Caiobook não encontrado"; exit 1; }
            
            # Se for um repositório git, atualiza o código; caso contrário, informe o usuário.
            if [ -d ".git" ]; then
              echo "Repositório encontrado. Atualizando..."
              git pull origin main
            else
              echo "Não é um repositório git. Verifique se o código foi clonado corretamente."
            fi
            
            # Cria o ambiente virtual se não existir
            if [ ! -d "venv" ]; then
              echo "Criando ambiente virtual..."
              python3 -m venv venv
            fi
            
            # Ativa o ambiente virtual e instala as dependências
            echo "Ativando ambiente virtual e instalando dependências..."
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            
            # Reinicia o serviço (verifique se o nome do serviço está correto)
            echo "Reiniciando o serviço..."
            sudo systemctl restart meu_notion.service || echo "Serviço 'meu_notion.service' não encontrado."
